//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from PulsarAsmGrammar.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="PulsarAsmGrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IPulsarAsmGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.bitness_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitness_directive([NotNull] PulsarAsmGrammarParser.Bitness_directiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.bitness_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitness_directive([NotNull] PulsarAsmGrammarParser.Bitness_directiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.address_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddress_directive([NotNull] PulsarAsmGrammarParser.Address_directiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.address_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddress_directive([NotNull] PulsarAsmGrammarParser.Address_directiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirective([NotNull] PulsarAsmGrammarParser.DirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirective([NotNull] PulsarAsmGrammarParser.DirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.proc_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProc_header([NotNull] PulsarAsmGrammarParser.Proc_headerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.proc_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProc_header([NotNull] PulsarAsmGrammarParser.Proc_headerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.instruction_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruction_specifier([NotNull] PulsarAsmGrammarParser.Instruction_specifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.instruction_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruction_specifier([NotNull] PulsarAsmGrammarParser.Instruction_specifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.unsigned_integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnsigned_integer([NotNull] PulsarAsmGrammarParser.Unsigned_integerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.unsigned_integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnsigned_integer([NotNull] PulsarAsmGrammarParser.Unsigned_integerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInteger([NotNull] PulsarAsmGrammarParser.IntegerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInteger([NotNull] PulsarAsmGrammarParser.IntegerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.data_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterData_definition([NotNull] PulsarAsmGrammarParser.Data_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.data_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitData_definition([NotNull] PulsarAsmGrammarParser.Data_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.data_definition_sequence_inner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterData_definition_sequence_inner([NotNull] PulsarAsmGrammarParser.Data_definition_sequence_innerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.data_definition_sequence_inner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitData_definition_sequence_inner([NotNull] PulsarAsmGrammarParser.Data_definition_sequence_innerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.data_definition_sequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterData_definition_sequence([NotNull] PulsarAsmGrammarParser.Data_definition_sequenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.data_definition_sequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitData_definition_sequence([NotNull] PulsarAsmGrammarParser.Data_definition_sequenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.data_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterData_identifier([NotNull] PulsarAsmGrammarParser.Data_identifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.data_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitData_identifier([NotNull] PulsarAsmGrammarParser.Data_identifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.data_definition_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterData_definition_statement([NotNull] PulsarAsmGrammarParser.Data_definition_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.data_definition_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitData_definition_statement([NotNull] PulsarAsmGrammarParser.Data_definition_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.op_immediate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_immediate([NotNull] PulsarAsmGrammarParser.Op_immediateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.op_immediate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_immediate([NotNull] PulsarAsmGrammarParser.Op_immediateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.op_register"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_register([NotNull] PulsarAsmGrammarParser.Op_registerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.op_register"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_register([NotNull] PulsarAsmGrammarParser.Op_registerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.op_imm_memory"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_imm_memory([NotNull] PulsarAsmGrammarParser.Op_imm_memoryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.op_imm_memory"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_imm_memory([NotNull] PulsarAsmGrammarParser.Op_imm_memoryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.op_indirect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_indirect([NotNull] PulsarAsmGrammarParser.Op_indirectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.op_indirect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_indirect([NotNull] PulsarAsmGrammarParser.Op_indirectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.op_local"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_local([NotNull] PulsarAsmGrammarParser.Op_localContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.op_local"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_local([NotNull] PulsarAsmGrammarParser.Op_localContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.op_base_w_offset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_base_w_offset([NotNull] PulsarAsmGrammarParser.Op_base_w_offsetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.op_base_w_offset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_base_w_offset([NotNull] PulsarAsmGrammarParser.Op_base_w_offsetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.op_base_w_register"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_base_w_register([NotNull] PulsarAsmGrammarParser.Op_base_w_registerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.op_base_w_register"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_base_w_register([NotNull] PulsarAsmGrammarParser.Op_base_w_registerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.op_relative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_relative([NotNull] PulsarAsmGrammarParser.Op_relativeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.op_relative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_relative([NotNull] PulsarAsmGrammarParser.Op_relativeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.op_data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_data([NotNull] PulsarAsmGrammarParser.Op_dataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.op_data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_data([NotNull] PulsarAsmGrammarParser.Op_dataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.jmp_operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJmp_operand([NotNull] PulsarAsmGrammarParser.Jmp_operandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.jmp_operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJmp_operand([NotNull] PulsarAsmGrammarParser.Jmp_operandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.st_operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSt_operand([NotNull] PulsarAsmGrammarParser.St_operandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.st_operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSt_operand([NotNull] PulsarAsmGrammarParser.St_operandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.operands"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperands([NotNull] PulsarAsmGrammarParser.OperandsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.operands"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperands([NotNull] PulsarAsmGrammarParser.OperandsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel([NotNull] PulsarAsmGrammarParser.LabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel([NotNull] PulsarAsmGrammarParser.LabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.instr_specifier_sequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr_specifier_sequence([NotNull] PulsarAsmGrammarParser.Instr_specifier_sequenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.instr_specifier_sequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr_specifier_sequence([NotNull] PulsarAsmGrammarParser.Instr_specifier_sequenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.instr_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr_body([NotNull] PulsarAsmGrammarParser.Instr_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.instr_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr_body([NotNull] PulsarAsmGrammarParser.Instr_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.jump_sequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJump_sequence([NotNull] PulsarAsmGrammarParser.Jump_sequenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.jump_sequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJump_sequence([NotNull] PulsarAsmGrammarParser.Jump_sequenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.conditional_body_shared"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditional_body_shared([NotNull] PulsarAsmGrammarParser.Conditional_body_sharedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.conditional_body_shared"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditional_body_shared([NotNull] PulsarAsmGrammarParser.Conditional_body_sharedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.conditional_instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditional_instruction([NotNull] PulsarAsmGrammarParser.Conditional_instructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.conditional_instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditional_instruction([NotNull] PulsarAsmGrammarParser.Conditional_instructionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.conditional_cp_instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditional_cp_instruction([NotNull] PulsarAsmGrammarParser.Conditional_cp_instructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.conditional_cp_instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditional_cp_instruction([NotNull] PulsarAsmGrammarParser.Conditional_cp_instructionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruction([NotNull] PulsarAsmGrammarParser.InstructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruction([NotNull] PulsarAsmGrammarParser.InstructionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.proc_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProc_element([NotNull] PulsarAsmGrammarParser.Proc_elementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.proc_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProc_element([NotNull] PulsarAsmGrammarParser.Proc_elementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.proc_element_sequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProc_element_sequence([NotNull] PulsarAsmGrammarParser.Proc_element_sequenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.proc_element_sequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProc_element_sequence([NotNull] PulsarAsmGrammarParser.Proc_element_sequenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.procedure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedure([NotNull] PulsarAsmGrammarParser.ProcedureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.procedure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedure([NotNull] PulsarAsmGrammarParser.ProcedureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.asm_file_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsm_file_element([NotNull] PulsarAsmGrammarParser.Asm_file_elementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.asm_file_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsm_file_element([NotNull] PulsarAsmGrammarParser.Asm_file_elementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.asm_file_element_sequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsm_file_element_sequence([NotNull] PulsarAsmGrammarParser.Asm_file_element_sequenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.asm_file_element_sequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsm_file_element_sequence([NotNull] PulsarAsmGrammarParser.Asm_file_element_sequenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.asm_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsm_file([NotNull] PulsarAsmGrammarParser.Asm_fileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.asm_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsm_file([NotNull] PulsarAsmGrammarParser.Asm_fileContext context);
}
