//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from PulsarAsmGrammar.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IPulsarAsmGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class PulsarAsmGrammarBaseListener : IPulsarAsmGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.bitness_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitness_directive([NotNull] PulsarAsmGrammarParser.Bitness_directiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.bitness_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitness_directive([NotNull] PulsarAsmGrammarParser.Bitness_directiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.address_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddress_directive([NotNull] PulsarAsmGrammarParser.Address_directiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.address_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddress_directive([NotNull] PulsarAsmGrammarParser.Address_directiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirective([NotNull] PulsarAsmGrammarParser.DirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirective([NotNull] PulsarAsmGrammarParser.DirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.proc_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProc_header([NotNull] PulsarAsmGrammarParser.Proc_headerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.proc_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProc_header([NotNull] PulsarAsmGrammarParser.Proc_headerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.instruction_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruction_specifier([NotNull] PulsarAsmGrammarParser.Instruction_specifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.instruction_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruction_specifier([NotNull] PulsarAsmGrammarParser.Instruction_specifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.unsigned_integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnsigned_integer([NotNull] PulsarAsmGrammarParser.Unsigned_integerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.unsigned_integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnsigned_integer([NotNull] PulsarAsmGrammarParser.Unsigned_integerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInteger([NotNull] PulsarAsmGrammarParser.IntegerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInteger([NotNull] PulsarAsmGrammarParser.IntegerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.data_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterData_definition([NotNull] PulsarAsmGrammarParser.Data_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.data_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitData_definition([NotNull] PulsarAsmGrammarParser.Data_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.data_definition_sequence_inner"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterData_definition_sequence_inner([NotNull] PulsarAsmGrammarParser.Data_definition_sequence_innerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.data_definition_sequence_inner"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitData_definition_sequence_inner([NotNull] PulsarAsmGrammarParser.Data_definition_sequence_innerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.data_definition_sequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterData_definition_sequence([NotNull] PulsarAsmGrammarParser.Data_definition_sequenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.data_definition_sequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitData_definition_sequence([NotNull] PulsarAsmGrammarParser.Data_definition_sequenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.data_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterData_identifier([NotNull] PulsarAsmGrammarParser.Data_identifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.data_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitData_identifier([NotNull] PulsarAsmGrammarParser.Data_identifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.data_definition_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterData_definition_statement([NotNull] PulsarAsmGrammarParser.Data_definition_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.data_definition_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitData_definition_statement([NotNull] PulsarAsmGrammarParser.Data_definition_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.op_immediate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_immediate([NotNull] PulsarAsmGrammarParser.Op_immediateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.op_immediate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_immediate([NotNull] PulsarAsmGrammarParser.Op_immediateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.op_register"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_register([NotNull] PulsarAsmGrammarParser.Op_registerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.op_register"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_register([NotNull] PulsarAsmGrammarParser.Op_registerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.op_imm_memory"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_imm_memory([NotNull] PulsarAsmGrammarParser.Op_imm_memoryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.op_imm_memory"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_imm_memory([NotNull] PulsarAsmGrammarParser.Op_imm_memoryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.op_indirect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_indirect([NotNull] PulsarAsmGrammarParser.Op_indirectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.op_indirect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_indirect([NotNull] PulsarAsmGrammarParser.Op_indirectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.op_local"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_local([NotNull] PulsarAsmGrammarParser.Op_localContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.op_local"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_local([NotNull] PulsarAsmGrammarParser.Op_localContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.op_base_w_offset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_base_w_offset([NotNull] PulsarAsmGrammarParser.Op_base_w_offsetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.op_base_w_offset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_base_w_offset([NotNull] PulsarAsmGrammarParser.Op_base_w_offsetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.op_base_w_register"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_base_w_register([NotNull] PulsarAsmGrammarParser.Op_base_w_registerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.op_base_w_register"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_base_w_register([NotNull] PulsarAsmGrammarParser.Op_base_w_registerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.op_relative"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_relative([NotNull] PulsarAsmGrammarParser.Op_relativeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.op_relative"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_relative([NotNull] PulsarAsmGrammarParser.Op_relativeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.op_data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_data([NotNull] PulsarAsmGrammarParser.Op_dataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.op_data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_data([NotNull] PulsarAsmGrammarParser.Op_dataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.jmp_operand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJmp_operand([NotNull] PulsarAsmGrammarParser.Jmp_operandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.jmp_operand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJmp_operand([NotNull] PulsarAsmGrammarParser.Jmp_operandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.st_operand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSt_operand([NotNull] PulsarAsmGrammarParser.St_operandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.st_operand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSt_operand([NotNull] PulsarAsmGrammarParser.St_operandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.operands"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperands([NotNull] PulsarAsmGrammarParser.OperandsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.operands"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperands([NotNull] PulsarAsmGrammarParser.OperandsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabel([NotNull] PulsarAsmGrammarParser.LabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabel([NotNull] PulsarAsmGrammarParser.LabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.instr_specifier_sequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstr_specifier_sequence([NotNull] PulsarAsmGrammarParser.Instr_specifier_sequenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.instr_specifier_sequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstr_specifier_sequence([NotNull] PulsarAsmGrammarParser.Instr_specifier_sequenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.instr_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstr_body([NotNull] PulsarAsmGrammarParser.Instr_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.instr_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstr_body([NotNull] PulsarAsmGrammarParser.Instr_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.jump_sequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJump_sequence([NotNull] PulsarAsmGrammarParser.Jump_sequenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.jump_sequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJump_sequence([NotNull] PulsarAsmGrammarParser.Jump_sequenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.conditional_body_shared"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditional_body_shared([NotNull] PulsarAsmGrammarParser.Conditional_body_sharedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.conditional_body_shared"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditional_body_shared([NotNull] PulsarAsmGrammarParser.Conditional_body_sharedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.conditional_instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditional_instruction([NotNull] PulsarAsmGrammarParser.Conditional_instructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.conditional_instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditional_instruction([NotNull] PulsarAsmGrammarParser.Conditional_instructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.conditional_cp_instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditional_cp_instruction([NotNull] PulsarAsmGrammarParser.Conditional_cp_instructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.conditional_cp_instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditional_cp_instruction([NotNull] PulsarAsmGrammarParser.Conditional_cp_instructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruction([NotNull] PulsarAsmGrammarParser.InstructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruction([NotNull] PulsarAsmGrammarParser.InstructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.proc_element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProc_element([NotNull] PulsarAsmGrammarParser.Proc_elementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.proc_element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProc_element([NotNull] PulsarAsmGrammarParser.Proc_elementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.proc_element_sequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProc_element_sequence([NotNull] PulsarAsmGrammarParser.Proc_element_sequenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.proc_element_sequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProc_element_sequence([NotNull] PulsarAsmGrammarParser.Proc_element_sequenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.procedure"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedure([NotNull] PulsarAsmGrammarParser.ProcedureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.procedure"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedure([NotNull] PulsarAsmGrammarParser.ProcedureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.asm_file_element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsm_file_element([NotNull] PulsarAsmGrammarParser.Asm_file_elementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.asm_file_element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsm_file_element([NotNull] PulsarAsmGrammarParser.Asm_file_elementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.asm_file_element_sequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsm_file_element_sequence([NotNull] PulsarAsmGrammarParser.Asm_file_element_sequenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.asm_file_element_sequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsm_file_element_sequence([NotNull] PulsarAsmGrammarParser.Asm_file_element_sequenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PulsarAsmGrammarParser.asm_file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsm_file([NotNull] PulsarAsmGrammarParser.Asm_fileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PulsarAsmGrammarParser.asm_file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsm_file([NotNull] PulsarAsmGrammarParser.Asm_fileContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
